### PR TITLE
Replace 32bit ctime_t with a 64bit microseconds_t in many placed

### LINKED ISSUE #268: austin fails to start on 32bit machines that have been running for more than an hour
I was looking into why austin would fail on armhf and armel in the Debian builds. It readily fails with:

    👾 It looks like you are trying to profile a process that is not a Python
    process. Make sure that you are targeting the right application. If the Python
    process is actually a child of the target process then use the -C option to
    discover it automatically.

Even when raising the timeout, it immediately fails like this. This suggests that something may be wrong with the timeout logic. I looked into what `gettime()` would return. Effectively, it tries to return the elapsed `CLOCK_BOOTIME` microseconds since epoch, which amounts to the number of microseconds since booting. The use of `1e6` performs a `float` promotion, so as the system is running longer and longer, the addition of `ts.tv_nsec / 1e3` will loose more and more precision. What's worse is that we're then converting that `float` to `ctime_t` aka `unsigned long` and that tends to become 0xffffffff for any timestamp. Hence, the timer immediately expires.

If we were to avoid the `float` promotion, we'd get signed integer overflows (aka undefined behavior). I locally prototyped what happens if I simply change `ctime_t` to be `unsigned long long` and then austin gets a lot further until it runs into the [i386 segfault](https://github.com/P403n1x87/austin/pull/266). After also fixing that, austin works, but austinp reproduces the [s390x failure](https://github.com/P403n1x87/austin/issues/267).

I'm not sure why this isn't a problem for i386, but I think it's due to i386 being the only 32bit architecture that has not been converted to time64.

Can we simply change `ctime_t` to be 64bit? (You need to fix a pile of format strings if you do.)

### PR DESCRIPTION
**Pull request by helmutg**
This makes austin work on 32bit time64 architectures such as armhf.

Closes: #268

### CODE REVIEW

File: src/linux/common.h [hunk 1]
```diff
@@ -59,15 +60,15 @@ struct _proc_extra_info {
...
 
     while (gettime() < end && (outcome = ptrace(request, pid, addr, data)) && errno == 3)
         sched_yield();
 
 #ifdef DEBUG
-    ctime_t wait = gettime() - end + 100000;
+    microseconds_t wait = gettime() - end + 100000;
     if (wait > 1000)
-        log_d("ptrace long wait for request %d: %ld microseconds", request, wait);
+        log_d("ptrace long wait for request %d: %" PRIu64 " microseconds", request, wait);
```
Comment (P403n1x87) [inline src/linux/common.h]: can we define a macro (essentially an alias) for `PRIu64`, e.g. `PRIus` to tie it to the type? This way we wouldn't need to know details about `microseconds_t` to choose the format string.

File: src/stats.c [hunk 2]
```diff
@@ -85,7 +87,7 @@ gettime() {
     clock_gettime(CLOCK_BOOTTIME, &ts);
 #endif
 
-    return ts.tv_sec * 1e6 + ts.tv_nsec / 1e3;
+    return ts.tv_sec * ((microseconds_t)1000000) + ts.tv_nsec / 100;
```
Comment (P403n1x87) [inline src/stats.c]:
```suggestion
    return ts.tv_sec * ((microseconds_t)1000000) + ts.tv_nsec / 1000;
```

File: src/stats.c [hunk 3]
```diff
@@ -99,7 +101,7 @@ stats_reset() {
     _sample_cnt = 0;
     _error_cnt  = 0;
 
-    _min_sampling_time = ULONG_MAX;
+    _min_sampling_time = UINT64_MAX;
```
Comment (P403n1x87) [inline src/stats.c]: maybe define `MICROSECONDS_MAX` as well?

**Comment by P403n1x87** [comment]
It looks like we have some wild metric outputs from CI with this change, but it's not immediately obvious to me why 🤔

File: src/linux/common.h (hunk 1 above)
Comment (helmutg) [reply src/linux/common.h]: Invading the `PRI*` macro space seems like a risky move to me. You suggested `MICROSECONDS_MAX` later and the code base uses `*_FMT` elsewhere, so I'll go for `MICROSECONDS_FMT` and hope you agree. It's a bit longer, but fairly obvious.

**Comment by helmutg** [comment]
Thank you fore the review and authorizing the workflows.  I believe that I have addressed all remarks.

**Comment by P403n1x87** [comment]
Thanks!
